FINAL TEST (hopefully)
- Hide private repo name
- Delete cloned repo after finished
- Re-enable test job

diff --git a/.github/workflows/1.16.1-build.yml b/.github/workflows/1.16.1-build.yml
--- a/.github/workflows/1.16.1-build.yml
+++ b/.github/workflows/1.16.1-build.yml
@@ -27,6 +27,13 @@ jobs:
     - name: Update CI Workspace
       uses: actions/checkout@v1
 
+    - name: Set up JDK 1.8
+      uses: actions/setup-java@v1
+      with:
+        java-version: 1.8
+        java-package: jdk
+        architecture: x64
+
     - name: Prepare to build The Midnight
       env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock
@@ -41,17 +48,11 @@ jobs:
           echo "mnKeyStoreAlias=${{ secrets.JKS_ALIAS }}" >> gradle.properties
           echo "mnKeyStorePass=${{ secrets.JKS_PASS }}" >> gradle.properties
           echo "mnKeyStoreKeyPass=${{ secrets.JKS_PASS }}" >> gradle.properties
-          cp Midnight-Private/${{ secrets.JKS_NAME }} MidnightAPI/${{ secrets.JKS_NAME }}
-          cp Midnight-Private/${{ secrets.JKS_NAME }} MidnightCore/${{ secrets.JKS_NAME }}
-          cp Midnight-Private/${{ secrets.JKS_NAME }} MidnightMod/${{ secrets.JKS_NAME }}
-
-
-    - name: Set up JDK 1.8
-      uses: actions/setup-java@v1
-      with:
-        java-version: 1.8
-        java-package: jdk
-        architecture: x64
+          cp ${{ secrets.PRIVATE_REPO_NAME }}/${{ secrets.JKS_NAME }} MidnightAPI/${{ secrets.JKS_NAME }}
+          cp ${{ secrets.PRIVATE_REPO_NAME }}/${{ secrets.JKS_NAME }} MidnightCore/${{ secrets.JKS_NAME }}
+          cp ${{ secrets.PRIVATE_REPO_NAME }}/${{ secrets.JKS_NAME }} MidnightMod/${{ secrets.JKS_NAME }}
+          rm -rf ${{ secrets.PRIVATE_REPO_NAME }}
+          echo "Ready to build and sign The Midnight!"
 
     - name: Build The Midnight
       uses: eskatos/gradle-command-action@v1
@@ -99,37 +100,37 @@ jobs:
         # A file, directory or wildcard pattern that describes what to upload
         path: MidnightMod/build/libs/*universal*.jar
 
-  # test:
+  test:
 
-  #   runs-on: ubuntu-latest
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #     - name: Update CI workspace
-  #       uses: actions/checkout@v1
+    steps:
+      - name: Update CI workspace
+        uses: actions/checkout@v1
 
-  #     - name: Set up JDK 1.8
-  #       uses: actions/setup-java@v1
-  #       with:
-  #         java-version: 1.8
-  #         java-package: jdk
-  #         architecture: x64
+      - name: Set up JDK 1.8
+        uses: actions/setup-java@v1
+        with:
+          java-version: 1.8
+          java-package: jdk
+          architecture: x64
 
-  #     - name: Set up test server
-  #       run: mkdir run; mkdir run/server; echo "eula=true" >> run/server/eula.txt; echo "Set eula to true."; echo "TEST FAILED" >> run/server/TESTSERVER.txt; echo "Generated TESTSERVER.txt file."
+      - name: Set up test server
+        run: mkdir run; mkdir run/server; echo "eula=true" >> run/server/eula.txt; echo "Set eula to true."; echo "TEST FAILED" >> run/server/TESTSERVER.txt; echo "Generated TESTSERVER.txt file."
 
-  #     - name: Run test server
-  #       uses: eskatos/gradle-command-action@v1
-  #       continue-on-error: true
-  #       with:
-  #         gradle-version: 4.10.3
-  #         arguments: runServer
+      - name: Run test server
+        uses: eskatos/gradle-command-action@v1
+        continue-on-error: true
+        with:
+          gradle-version: 4.10.3
+          arguments: runServer
 
-  #     - name: Read server test result
-  #       id: log
-  #       uses: andstor/file-reader-action@v1
-  #       with:
-  #         path: run/server/TESTSERVER.txt
+      - name: Read server test result
+        id: log
+        uses: andstor/file-reader-action@v1
+        with:
+          path: run/server/TESTSERVER.txt
 
-  #     - name: Determine if server test was unsuccessful
-  #       if: contains(steps.log.outputs.contents, 'TEST FAILED')
-  #       run: echo "GitHub Actions was unable to successfully load the test server into a temporary world. Check the log in the \"Run test server\" step to see what went wrong."; exit 1
+      - name: Determine if server test was unsuccessful
+        if: contains(steps.log.outputs.contents, 'TEST FAILED')
+        run: echo "GitHub Actions was unable to successfully load the test server into a temporary world. Check the log in the \"Run test server\" step to see what went wrong."; exit 1
