FINAL COMMIT

diff --git a/.github/workflows/1.16.1-build.yml b/.github/workflows/1.16.1-build.yml
--- a/.github/workflows/1.16.1-build.yml
+++ b/.github/workflows/1.16.1-build.yml
@@ -8,6 +8,7 @@ on:
     branches:
       - 1.16.1
     paths-ignore:
+      - '.github/**'
       - 'curseforge/**'
       - 'README.md'
       - 'LICENSE'
@@ -79,7 +80,7 @@ jobs:
           architecture: x64
 
       - name: Set up test server
-        run: mkdir run; mkdir run/server; echo "eula=false" >> run/server/eula.txt; echo "Set eula to true."; echo "TEST FAILED" >> run/server/TESTSERVER.txt; echo "Generated TESTSERVER.txt file."
+        run: mkdir run; mkdir run/server; echo "eula=true" >> run/server/eula.txt; echo "Set eula to true."; echo "TEST FAILED" >> run/server/TESTSERVER.txt; echo "Generated TESTSERVER.txt file."
 
       - name: Run test server
         uses: eskatos/gradle-command-action@v1
@@ -101,7 +102,7 @@ jobs:
 
       - name: Check if server test was unsuccessful
         if: contains(steps.log.outputs.contents, 'TEST FAILED')
-        run: echo "GitHub Actions was unable to successfully load the test server into a temporary world. Check the log in the \"Run test server\" step to see what went wrong.";
+        run: echo "GitHub Actions was unable to successfully load the test server into a temporary world. Check the log in the \"Run test server\" step to see what went wrong."; exit 1
 
       - name: Check if server test was successful
         if: contains(steps.log.outputs.contents, 'TEST SUCCESS')
